import Link from 'next/link'
import { ArrowRight, Check, Clock3, MapPin, ShieldCheck, Sparkles, Phone } from 'lucide-react'
import { business, faqs, serviceAreas, services } from '@/lib/site-data'

const heroImage = '/images/Porta potty photos/quick-delivery-porta-potty-rental.jpg'

export function SectionIntro({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div> }

export function HomePage() { return <main>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">East Orange, NJ · Local delivery</span><h1>Clean restrooms.<br /><em>Zero hassle.</em></h1><p className="hero-lede">Portable toilet rentals that arrive on time, stay fresh, and fit the way your project or event actually works.</p><div className="hero-actions"><a className="button button-primary" href={business.phoneHref}><Phone size={18} /> Get a quote by phone</a><Link className="text-link" href="/services">Explore services <ArrowRight size={17} /></Link></div><div className="trust-line"><span><Check size={16} /> Locally operated</span><span><Check size={16} /> Clear pricing</span><span><Check size={16} /> On-time delivery</span></div></div><div className="hero-image"><img src={heroImage} alt="Clean portable restroom ready for delivery" /><div className="image-note"><strong>Ready when you are.</strong><span>Ask about availability for your date.</span></div></div></div></section>
  <section className="proof-strip"><div className="container proof-grid"><div><strong>7am–7pm</strong><span>Mon–Sat support</span></div><div><strong>Essex County</strong><span>Local delivery area</span></div><div><strong>8 ways</strong><span>to solve your restroom need</span></div><div><strong>One call</strong><span>to get started</span></div></div></section>
  <section className="section"><div className="container"><SectionIntro eyebrow="A better rental experience" title="The right restroom, in the right place, without the runaround." copy="Whether you are managing a busy job site or welcoming neighbors to an outdoor event, we make portable sanitation feel simple. Tell us what is happening, where it is happening, and when you need it—we will help you build a practical setup." /><div className="service-grid">{services.slice(0, 4).map((s, i) => <Link className="service-card" href={`/${s.slug}`} key={s.slug}><div className="service-card-image"><img src={s.image} alt={s.short} /><span>0{i + 1}</span></div><div><h3>{s.short}</h3><p>{s.blurb}</p><span className="card-link">See service <ArrowRight size={16} /></span></div></Link>)}</div><div className="center-link"><Link className="button button-outline" href="/services">View all services <ArrowRight size={17} /></Link></div></div></section>
  <section className="split-section"><div className="container split-grid"><div className="split-photo"><img src="/images/Porta potty photos/porta-potty-rental-team.png" alt="Portable restroom rental team" /></div><div><span className="eyebrow">Built around your day</span><h2>Helpful from the first hello to the final pickup.</h2><p>Great service is not just a clean unit. It is a delivery that works around your access, a team that answers the phone, and a plan that does not leave you guessing.</p><ul className="check-list"><li><ShieldCheck /> Units selected for your guests or crew</li><li><MapPin /> Thoughtful placement for smooth site flow</li><li><Clock3 /> Scheduling that respects your timeline</li></ul><Link className="text-link" href="/about">Why local teams choose us <ArrowRight size={17} /></Link></div></div></section>
  <section className="cta-section"><div className="container cta-inner"><div><span className="eyebrow">Your next step</span><h2>Have a date in mind?</h2><p>Call and tell us what you need. We will talk through options and availability.</p></div><a className="button button-light" href={business.phoneHref}><Phone size={18} /> {business.phone}</a></div></section>
</main> }

export function ServicesPage() { return <main><PageHero eyebrow="Services" title="Portable sanitation for real life in East Orange." copy="From a single backyard gathering to a multi-month construction project, choose the setup that makes your day easier." image="/images/Porta potty photos/Porta Potty Rental Services.png" /><section className="section"><div className="container"><div className="service-grid service-grid-wide">{services.map((s, i) => <Link className="service-card" href={`/${s.slug}`} key={s.slug}><div className="service-card-image"><img src={s.image} alt={s.short} /><span>{String(i + 1).padStart(2, '0')}</span></div><div><h3>{s.short}</h3><p>{s.blurb}</p><span className="card-link">Learn more <ArrowRight size={16} /></span></div></Link>)}</div></div></section></main> }

export function PageHero({ eyebrow, title, copy, image }: { eyebrow: string; title: string; copy: string; image: string }) { return <section className="page-hero"><div className="container page-hero-grid"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div><img src={image} alt="Portable restroom rental" /></div></section> }

export function ServicePage({ service }: { service: typeof services[number] }) { return <main><PageHero eyebrow="Portable sanitation service" title={service.title} copy={service.blurb} image={service.image} /><section className="section"><div className="container article-grid"><article><p className="lead">{service.body}</p><h2>Service that makes the logistics feel lighter</h2><p>Renting a portable restroom should not require a crash course in sanitation. We ask a few practical questions—how many people will use it, how long it will be there, what access looks like, and what kind of experience you want—and recommend a setup that fits.</p><p>For East Orange homeowners, event hosts, contractors, property managers, and local organizations, that means dependable equipment and a clear point of contact. We work with the details that can make a delivery go smoothly: a level location, a sensible route for the service vehicle, and placement that is convenient without becoming the center of attention.</p><h2>A straightforward rental process</h2><div className="process"><div><b>01</b><h3>Tell us the plan</h3><p>Share your address, date, guest or crew count, and any special requirements.</p></div><div><b>02</b><h3>Choose your setup</h3><p>We help match the unit, accessories, and service frequency to your situation.</p></div><div><b>03</b><h3>We handle delivery</h3><p>Your unit arrives ready to use, with pickup and recurring service discussed upfront.</p></div></div><h2>Designed for East Orange and nearby communities</h2><p>Local conditions matter. A narrow driveway, an active work zone, a school field, or a busy neighborhood event each calls for a slightly different plan. Because we serve East Orange and surrounding Essex County communities, you get a team that understands local routes, timing, and the importance of being easy to reach.</p><p>Need help deciding? Call <a className="inline-link" href={business.phoneHref}>{business.phone}</a>. We will help you think it through without pressure.</p></article><aside className="aside-card"><Sparkles size={20} /><h3>Good to know</h3><p>We can pair portable toilets with handwashing stations, accessible units, and recurring service when your project needs more than a one-day delivery.</p><Link className="text-link" href="/contact">Ask about your setup <ArrowRight size={16} /></Link></aside></div></section><section className="faq-section"><div className="container"><SectionIntro eyebrow="Common questions" title="Before you book" copy="A few answers to help you plan with confidence." /><div className="faq-grid">{faqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section></main> }

export function AboutPage() { return <main><PageHero eyebrow="Why choose us" title="A local partner for the unglamorous essentials." copy="We believe reliable portable sanitation should feel personal, clear, and easy to plan." image="/images/Porta potty photos/about-us.jpg" /><section className="section"><div className="container narrow-copy"><span className="eyebrow">The East Orange difference</span><h2>We make a necessary service feel like good service.</h2><p>Portable restrooms are not usually the headline of a project or celebration. They are part of the infrastructure that lets everything else happen comfortably. Our job is to make that infrastructure dependable.</p><p>That means honest conversations, clean equipment, careful placement, and follow-through. We serve local homeowners, contractors, event organizers, schools, nonprofits, and businesses that need a restroom solution without adding another source of stress.</p><div className="values-grid"><div><ShieldCheck /><h3>Dependable</h3><p>We respect your date, access instructions, and the people counting on the setup.</p></div><div><MapPin /><h3>Local</h3><p>East Orange is home base, and nearby Essex County communities are part of our everyday service area.</p></div><div><Sparkles /><h3>Clean-minded</h3><p>We focus on presentation, usability, and the small details guests notice.</p></div></div></div></section><section className="area-section"><div className="container"><SectionIntro eyebrow="Where we deliver" title="Close to home, close to your project." copy="We serve East Orange and surrounding communities across Essex County. If you are nearby and have a specific location question, call us." /><div className="area-pills">{serviceAreas.map(area => <span key={area}>{area}</span>)}</div></div></section></main> }

export function ContactPage() { return <main><PageHero eyebrow="Contact" title="Let’s talk about what you need." copy="The quickest way to check availability is to call. You can also email us with your date, location, and a few details about the project or event." image="/images/Porta potty photos/contact-us.png" /><section className="section"><div className="container contact-grid"><div><span className="eyebrow">Reach our team</span><h2>One call gets the conversation started.</h2><p>We are happy to help you compare options, estimate quantities, and plan placement. No complicated form required.</p><a className="contact-line" href={business.phoneHref}><Phone /> <span><small>Call us</small>{business.phone}</span></a><a className="contact-line" href={`mailto:${business.email}`}><span className="contact-icon">@</span> <span><small>Email</small>{business.email}</span></a><div className="contact-line"><MapPin /> <span><small>Office</small>{business.address}</span></div><div className="contact-line"><Clock3 /> <span><small>Hours</small>{business.hours}</span></div></div><div className="contact-card"><h3>Have these details ready</h3><ul className="check-list"><li><Check /> Delivery address or neighborhood</li><li><Check /> Date and rental length</li><li><Check /> Estimated guests or crew</li><li><Check /> Accessibility or handwashing needs</li></ul><a className="button button-primary" href={business.phoneHref}><Phone size={18} /> Call for availability</a></div></div></section></main> }

export function EmergencyPage() { return <main><section className="emergency-hero"><div className="container"><span className="eyebrow">Urgent restroom coverage</span><h1>Need a portable restroom fast?</h1><p>Call East Orange Porta Potty Rentals and tell us what happened. We will check availability and help you find the most practical next move.</p><a className="button button-light" href={business.phoneHref}><Phone size={18} /> Call {business.phone}</a></div></section><section className="section"><div className="container narrow-copy"><span className="eyebrow">When plans change</span><h2>Fast help starts with a clear picture.</h2><p>Construction schedules shift. A venue can lose access to its plumbing. A storm or unexpected repair can turn a normal day into a sanitation problem. In those moments, a quick phone conversation is more useful than a long form.</p><p>Tell us your location, how many people need coverage, and how soon you need a solution. We will be direct about availability and talk through standard units, accessible restrooms, handwashing stations, or trailer options when appropriate.</p><Link className="text-link" href="/contact">See all contact details <ArrowRight size={17} /></Link></div></section></main> }
